/**:
  ros__parameters:
    harf_pose:
      position.x: 89657.3262 #89653.7
      position.y: 43176.6794 #43122.5
      position.z: -28.0
      orientation.x: 0.0
      orientation.y: 0.0
      orientation.z: -0.90
      orientation.w: 0.25

    pit_stop_pose:
      position.x: 89626.3671875
      position.y: 43134.921875
      position.z: 42.1
      orientation.x: 0.0
      orientation.y: -0.0
      orientation.z: -0.8788172006607056
      orientation.w: -0.47715866565704346
