/**:
  ros__parameters:
    harf_pose:
      position.x: 89652.1413 #89653.7
      position.y: 43123.2711 #43122.5
      position.z: 0.0
      orientation.x: 0.0
      orientation.y: 0.0
      orientation.z: -0.971732
      orientation.w: 0.236088

    pit_stop_pose:
      position.x: 89657.3262
      position.y: 43176.6794
      position.z: -28.0
      orientation.x: 0.0
      orientation.y: -0.0
      orientation.z: -0.9
      orientation.w: 0.25
