/**:
  ros__parameters:
    planning_algorithm: "astar"
    waypoints_velocity: 30.0
    update_rate: 5.0
    th_arrived_distance_m: 1.0
    th_stopped_time_sec: 1.0
    th_stopped_velocity_mps: 0.01
    th_course_out_distance_m: 1.0
    vehicle_shape_margin_m: 1.0
    replan_when_obstacle_found: true
    replan_when_course_out: true

    time_limit: 1000000.0
    minimum_turning_radius: 5.0
    maximum_turning_radius: 15.0
    turning_radius_size: 10

    theta_size: 180
    angle_goal_range: 6.0
    curve_weight: 1.5 #1.2
    reverse_weight: 2.0
    lateral_goal_range: 1.0
    longitudinal_goal_range: 3.0

    obstacle_threshold: 100

    astar:
      only_behind_solutions: false
      use_back: false
      distance_heuristic_weight: 0.7 #1.0 

