/**:
  ros__parameters:
    outside_cost: 127
    wall_inflation_radius: 5.0
    wall_min_cost: -100.0
    wall_max_cost: 100.0

    object_inside_cost: 100
    object_inside_radius: 0.6
    object_inflation_radius: 3.0
    object_min_cost: -128.0
    objcet_max_cost: 70.0

