/**:
  ros__parameters:
    outside_cost: 127
    wall_inflation_radius: 0.5
    wall_min_cost: 101
    wall_max_cost: 120

    object_inside_cost: 100
    object_inflation_radius: 4.0
    object_min_cost: 0
    object_max_cost: 100

    object_long_side: 3.0
    object_short_side: 1.5