/**:
  ros__parameters:
    outside_cost: 127
    wall_inflation_radius: 2.0
    wall_min_cost: 0
    wall_max_cost: 0

    object_inside_cost: 100
    object_inside_radius: 1.0
    inside_min_cost: 70
    inside_max_cost: 100
    object_inflation_radius: 1.5
    object_min_cost: 20
    object_max_cost: 100

    object_long_side: 2.0
    object_short_side: 1.0