/**:
  ros__parameters:
    outside_cost: 127.0
    wall_inflation_radius: 7.0
    wall_min_cost: -128.0
    wall_max_cost: 80.0

    object_inside_cost: 100.0
    object_inside_radius: 0.6
    object_inflation_radius: 6.0
    object_min_cost: -128.0
    object_max_cost: 80.0

