/**:
  ros__parameters:
    threshold: 220.0
    attract: 15.0
    repulse: 500.0
    penalty_dist: 1.0

    desired_dist: 0.5
    start_index: 5
    num_change_points: 10
    lookahead_dist: 2.0

    angle_interval: 2.0
    max_angle: 24.0
    min_angle: -24.0
    near_point_dist: 1.0
