/**:
  ros__parameters:
    attract: 20.0
    repulse: 500.0
    forward_dist: 1.5
    side_dist: 1.5

    desired_dist: 0.8
    start_index: 10
    num_change_points: 20
    lookahead_dist: 0.5

    angle_interval: 2.0
    max_angle: 24.0
    min_angle: -24.0
    margin: 40

    visual: false

