/**:
  ros__parameters:
    threshold: 20.0 # 消す
    attract: 20.0
    repulse: 500.0
    penalty_dist: 1.5 # 消す
    forward_dist: 3.0
    side_dist: 1.0

    desired_dist: 1.0
    start_index: 10
    num_change_points: 20
    lookahead_dist: 1.5

    angle_interval: 2.0
    max_angle: 24.0
    min_angle: -24.0
    near_point_dist: -129.0 # 消す
    margin: 40

    visual: true
    visual_angle: 0.0

    min: 20.0
    max: 40.0
